apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: goods-mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: payment
          image: ghcr.io/prgrms-be-adv-devcourse/beadv5_2_todaylunchmenu_be/payment:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
            - configMapRef:
                name: payment-config
            - secretRef:
                name: payment-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            failureThreshold: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
