apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: goods-mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      nodeSelector:
        role: app
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: product
          image: ghcr.io/sihoney/goodsmall-be/product:latest
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms192m -Xmx384m -Duser.timezone=Asia/Seoul"
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
            - configMapRef:
                name: product-config
            - secretRef:
                name: product-secret
          startupProbe:
            tcpSocket:
              port: 8081
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
