apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: goods-mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        role: infra
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.0
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_4LW_COMMANDS_WHITELIST
              value: "*"
          startupProbe:
            tcpSocket:
              port: 2181
            failureThreshold: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 20
            periodSeconds: 10
