apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
  namespace: goods-mall
data:
  API_GATEWAY_HOST: "http://gateway:8080"
  SERVICES_ORDER_URL: "http://order:8084"
  SERVICES_PAYMENT_URL: "http://payment:8082"
  SERVICES_PRODUCT_URL: "http://product:8081"
  SERVICES_AUCTION_URL: "http://auction:8090"
  SERVICES_SETTLEMENT_URL: "http://settlement:8085"
  FRONTEND_BASE_URL: "https://goods-mall-fe.vercel.app"
  MEMBER_SIGNUP_REQUIRE_EMAIL_VERIFICATION: "true"
  EMAIL_PROVIDER: "smtp"
  SMTP_HOST: "live.smtp.mailtrap.io"
  SMTP_PORT: "587"
  KAKAO_CLIENT_ID: "40bcc2744d37da5ed008a7a22fe45b7a"
