apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
  namespace: goods-mall
data:
  SPRING_PROFILES_ACTIVE: "prod"
  API_GATEWAY_HOST: "http://gateway:8080"
  OAUTH_REDIRECT_BASE_URL: "https://54.116.150.154.nip.io"
  SERVICES_ORDER_URL: "http://order:8084"
  SERVICES_PAYMENT_URL: "http://payment:8082"
  SERVICES_PRODUCT_URL: "http://product:8081"
  SERVICES_AUCTION_URL: "http://auction:8090"
  SERVICES_SETTLEMENT_URL: "http://settlement:8085"
  FRONTEND_BASE_URL: "https://goods-mall-fe.vercel.app"
  REFRESH_TOKEN_COOKIE_SAME_SITE: "None"
  REFRESH_TOKEN_COOKIE_SECURE: "true"
  MEMBER_SIGNUP_REQUIRE_EMAIL_VERIFICATION: "true"
  SMTP_HOST: "live.smtp.mailtrap.io"
  SMTP_PORT: "587"
  SMTP_AUTH: "true"
  SMTP_STARTTLS_ENABLE: "true"
  KAKAO_CLIENT_ID: "40bcc2744d37da5ed008a7a22fe45b7a"
