apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: goods-mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: order
          image: ghcr.io/prgrms-be-adv-devcourse/beadv5_2_todaylunchmenu_be/order:latest
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secret
          startupProbe:
            tcpSocket:
              port: 8084
            failureThreshold: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
