apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: goods-mall
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DB_URL: "jdbc:postgresql://postgres:5432/goods_mall"

