apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=mmsgod0427@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
    ports:
      websecure:
        expose:
          default: true
    persistence:
      enabled: true
      size: 128Mi
