spring:
    application:
        name: product-service

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/product_db
        username: postgres      # PostgreSQL 계정
        password: postgres      # PostgreSQL 비밀번호

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

    server:
        port: 8081

    logging:
        level:
            com.example.product: DEBUG
            org.hibernate.SQL: DEBUG
