apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
  namespace: goods-mall
data:
  API_GATEWAY_HOST: "http://gateway:8080"
  AWS_REGION: "ap-northeast-2"
  MEMBER_SIGNUP_REQUIRE_EMAIL_VERIFICATION: "true"

  EMAIL_PROVIDER: "smtp"
  SMTP_HOST: "live.smtp.mailtrap.io"
  SMTP_PORT: "587"

  SMTP_AUTH: "true"
  SMTP_STARTTLS_ENABLE: "true"
  # TODO: 도메인 인증 완료 후 MAIL_FROM 을 실제 인증된 발신 주소로 변경
  MAIL_FROM: "no-reply@goods-mall.shop"
  MAIL_FROM_NAME: "Goods Mall"

  EMAIL_VERIFICATION_FRONTEND_URL: "https://goodsmall.vercel.app/email-verification"

  PASSWORD_RESET_FRONTEND_URL: "https://goodsmall.vercel.app/password-reset"

  KAKAO_REDIRECT_URI: "http://3.36.235.7/api/auth/oauth/kakao/callback"
  KAKAO_CLIENT_ID: "40bcc2744d37da5ed008a7a22fe45b7a"
  KAKAO_FRONTEND_CALLBACK_URL: "https://goodsmall.vercel.app/auth/kakao/callback"

  AWS_S3_BUCKET: "todaylunchmenu"
