server:
    port: 8080

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                - id: product-service
                  uri: lb://product-service
                  predicates:
                      - Path=/api/products/**

                - id: member-service
                  uri: lb://member-service
                  predicates:
                      - Path=/api/members/**

                - id: order-service
                  uri: lb://order-service
                  predicates:
                      - Path=/api/orders/**

                - id: payment-service
                  uri: lb://payment-service
                  predicates:
                      - Path=/api/payments/**

                - id: settlement-service
                  uri: lb://settlement-service
                  predicates:
                      - Path=/api/settlements/**

                - id: notification-service
                  uri: lb://notification-service
                  predicates:
                      - Path=/api/notifications/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
