apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-config
  namespace: goods-mall
data:
  AWS_S3_BUCKET: "todaylunchmenu"
  ELASTICSEARCH_URI: "http://elasticsearch:9200"
  SERVICES_PAYMENT_URL: "http://payment:8082"
