apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: goods-mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: notification
          image: ghcr.io/prgrms-be-adv-devcourse/beadv5_2_todaylunchmenu_be/notification:latest
          ports:
            - containerPort: 8087
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms192m -Xmx384m -Duser.timezone=Asia/Seoul"
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
