apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: goods-mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gateway
          image: ghcr.io/sihoney/goodsmall-be/gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms192m -Xmx384m -Duser.timezone=Asia/Seoul"
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
            - configMapRef:
                name: gateway-config
            - secretRef:
                name: gateway-secret
          volumeMounts:
            - name: gateway-auth-rules-config
              mountPath: /config/gateway-auth-rules.yml
              subPath: gateway-auth-rules.yml
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: gateway-auth-rules-config
          configMap:
            name: gateway-auth-rules-config
