apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: goods-mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gateway
          image: ghcr.io/prgrms-be-adv-devcourse/beadv5_2_todaylunchmenu_be/gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
            - configMapRef:
                name: gateway-config
            - secretRef:
                name: gateway-secret
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
