spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        default_schema: settlement
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.settlement.infrastructure.messaging.kafka.contract

server:
  port: 8085

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

settlement:
  kafka:
    topics:
      settlement-candidate-created: ${SETTLEMENT_KAFKA_TOPIC_SETTLEMENT_CANDIDATE_CREATED:payment.settlement-candidate-created}
      settlement-payout-requested: ${SETTLEMENT_KAFKA_TOPIC_SETTLEMENT_PAYOUT_REQUESTED:settlement.seller-payout-requested}
      settlement-payout-result: ${SETTLEMENT_KAFKA_TOPIC_SETTLEMENT_PAYOUT_RESULT:payment.seller-payout-result}
    consumer-groups:
      settlement-candidate-created: ${SETTLEMENT_KAFKA_CONSUMER_GROUP_SETTLEMENT_CANDIDATE_CREATED:settlement-service}
      settlement-payout-result: ${SETTLEMENT_KAFKA_CONSUMER_GROUP_SETTLEMENT_PAYOUT_RESULT:settlement-service}
    retry:
      settlement-candidate-created:
        dlq-topic: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_CANDIDATE_CREATED_DLQ_TOPIC:payment.settlement-candidate-created.dlq}
        initial-interval-ms: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_CANDIDATE_CREATED_INITIAL_INTERVAL_MS:1000}
        multiplier: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_CANDIDATE_CREATED_MULTIPLIER:2.0}
        max-interval-ms: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_CANDIDATE_CREATED_MAX_INTERVAL_MS:10000}
        max-retries: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_CANDIDATE_CREATED_MAX_RETRIES:3}
      settlement-payout-result:
        dlq-topic: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_PAYOUT_RESULT_DLQ_TOPIC:payment.seller-payout-result.dlq}
        initial-interval-ms: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_PAYOUT_RESULT_INITIAL_INTERVAL_MS:1000}
        multiplier: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_PAYOUT_RESULT_MULTIPLIER:2.0}
        max-interval-ms: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_PAYOUT_RESULT_MAX_INTERVAL_MS:10000}
        max-retries: ${SETTLEMENT_KAFKA_RETRY_SETTLEMENT_PAYOUT_RESULT_MAX_RETRIES:3}
  batch:
    monthly-aggregation:
      cron: ${SETTLEMENT_BATCH_MONTHLY_AGGREGATION_CRON:0 5 3 1 * *}
      zone: ${SETTLEMENT_BATCH_MONTHLY_AGGREGATION_ZONE:Asia/Seoul}
    retryable-failed-payout:
      cron: ${SETTLEMENT_BATCH_RETRYABLE_FAILED_PAYOUT_CRON:0 */10 * * * *}
      zone: ${SETTLEMENT_BATCH_RETRYABLE_FAILED_PAYOUT_ZONE:Asia/Seoul}

