apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement
  namespace: goods-mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settlement
  template:
    metadata:
      labels:
        app: settlement
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: settlement
          image: ghcr.io/prgrms-be-adv-devcourse/beadv5_2_todaylunchmenu_be/settlement:latest
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          startupProbe:
            tcpSocket:
              port: 8085
            failureThreshold: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
