apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: goods-mall
data:
  FRONTEND_BASE_URL: "https://www.goods-mall.shop"
  SERVICES_ORDER_URL: "http://order:8084"
  TOSS_PAYMENTS_CLIENT_KEY: "test_ck_DLJOpm5QrldyeOMlna9QrPNdxbWn"
  HIKARI_MAX_POOL_SIZE: "20"
