apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: goods-mall
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: db-migration
          image: ghcr.io/prgrms-be-adv-devcourse/beadv5_2_todaylunchmenu_be/db-migration:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
