apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: goods-mall
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      nodeSelector:
        role: infra
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config
          startupProbe:
            tcpSocket:
              port: 9092
            failureThreshold: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 10
